// <auto-generated />
using GameStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.API.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20250725151416_NewGames")]
    partial class NewGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("GameStore.API.Entities.Game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            id = 1,
                            GenreId = 1,
                            Name = "Street Fighter",
                            Price = 19.99m
                        },
                        new
                        {
                            id = 2,
                            GenreId = 2,
                            Name = "FIFA",
                            Price = 29.99m
                        },
                        new
                        {
                            id = 3,
                            GenreId = 3,
                            Name = "GTA",
                            Price = 49.99m
                        });
                });

            modelBuilder.Entity("GameStore.API.Entities.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Fighting"
                        },
                        new
                        {
                            id = 2,
                            Name = "Sports"
                        },
                        new
                        {
                            id = 3,
                            Name = "Open-Wrld"
                        },
                        new
                        {
                            id = 4,
                            Name = "Bom"
                        });
                });

            modelBuilder.Entity("GameStore.API.Entities.Game", b =>
                {
                    b.HasOne("GameStore.API.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
